### ISSUE TITLE
Cannot access the Dead letter queues

### ISSUE THREAD

**Issue by svonidze** [weloytty/MSMQ.Messaging#12]
Cannot access the Dead letter queue and the Transactional Dead letter queue
```csharp
// .\system$;DeadXact
// .\system$;DeadLetter.
string deadLetterQueuePath = @".\System$;Deadletter";

// falls with Invalid queue path name
if (!MessageQueue.Exists(sourceQueuePath)) { ... }
```
the error with stack trace
```csharp
Invalid queue path name. 
MessageQueueErrorCode: IllegalQueuePathName 

   at MSMQ.Messaging.MessageQueue.ResolveFormatNameFromQueuePath(String queuePath, Boolean throwException)
   at MSMQ.Messaging.MessageQueue.Exists(String path)
```

found the source code check 
```csharp
private static string ResolveFormatNameFromQueuePath(string queuePath, bool throwException)
        {
            string machine = queuePath.Substring(0, queuePath.IndexOf('\\'));
            //The name includes the \\
            string name = queuePath.Substring(queuePath.IndexOf('\\'));
            //Check for machine DeadLetter or Journal
            if (String.Compare(name, SUFIX_DEADLETTER, true, CultureInfo.InvariantCulture) == 0 ||
                String.Compare(name, SUFIX_DEADXACT, true, CultureInfo.InvariantCulture) == 0 ||
                String.Compare(name, SUFIX_JOURNAL, true, CultureInfo.InvariantCulture) == 0)
            {
```
so it expects the path contains SUFIX_XXX 
if I changed  `string queuePath = ".\\Deadletter$";` in my code to satisfy the checks then got
```
UnsupportedOperation
A workgroup installation computer does not support the operation.

   at MSMQ.Messaging.MessageQueue.GetMachineId(String machineName)
   at MSMQ.Messaging.MessageQueue.ResolveFormatNameFromQueuePath(String queuePath, Boolean throwException)
   at MSMQ.Messaging.MessageQueue.Exists(String path)
```

**Comment by svonidze** [comment]
no problem with code, the reason of the issue was wrong Dead Letter queue names.

Found the correct name of Dead Letter queue - `FormatName:DIRECT=OS:.\\SYSTEM$;DEADLETTER`
thanks to the PowerShell command 
```
Get-MsmqQueue -QueueType SystemDeadLetter
```
